### ISSUE TITLE
Collect, preprocess dataset(combined 1600-1900) + testsets

### ISSUE THREAD

**Issue by Borg93** [Borg93/TrOCR#2]
# Description:

Collect HTR data, transform it to correct format for a TrOCR model (HuggingFace). Collect HTR data including all testsets.

## Requirements / Acceptance Criteria:

- Sucessfully loaded dataset with a huggingface dataloader.
- Splitted into a train and test.

## Design and Technical Notes:

- All data is on the 12tb external harddrive. Ask Erik. Currently hooked to Erik's computer

# Subtasks:

- [ ] Check dataset format for TrOCR model on huggingface
- [ ] Move data to a testable place (from external harddrive
- [ ] Transform data to correct format
- [ ] Store data as train and split
- [ ] Create a dataloader

**Comment by Borg93** [comment]
JAg har pratat med den snubben. Bolen ligger hos david
